version: "3"

services:

  runtime-setup:
    image: sswg-collection:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: sswg-collection:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
      - ../.cache:/cache:z
      - ../.output:/.output:z
      - ${PRIVATE_KEY_PATH:-../certs/private.pem}:/certs/private.pem:z
      - ${SIGNING_CERT_PATH:-../certs/signing.cer}:/certs/signing.cer:z
      - ${INTERMEDIATE_CERT_PATH:-../certs/intermediate.cer}:/certs/intermediate.cer:z
      - ${ROOT_CERT_PATH:-../certs/root.cer}:/certs/root.cer:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  generate:
    <<: *common
    command:
      - /bin/bash
      - -clx
      - |
          package-collection-generate \
          packages.json \
          ${OUTPUT:-.output/collection.json} \
          --working-directory-path /cache \
          --auth-token github:github.com:${GITHUB_API_TOKEN} \
          --verbose

  diff:
    <<: *common
    command:
      - /bin/bash
      - -clx
      - |
          package-collection-diff \
          ${INPUT1:-collection.json} \
          ${INPUT2:-.output/collection.json} \
          | tee ${OUTPUT:-.output/diff}

  sign:
    <<: *common
    command:
      - /bin/bash
      - -clx
      - |
          package-collection-sign \
          --verbose \
          ${INPUT:-.output/collection.json} \
          ${OUPUT:-.output/collection-signed.json} \
          /certs/private.pem \
          /certs/signing.cer \
          /certs/intermediate.cer \
          /certs/root.cer

  shell:
    <<: *common
    entrypoint: /bin/bash -l
